### ISSUE TITLE
Err tunnel connection fails

### ISSUE THREAD

**Issue by BIGS772** [KevinBytesTheDust/CVAmp#292]
**Please answer the following questions:**
- CVAmp version 7.1
- OS with version? 11
- Streaming platform? Twitch
- Proxies from webshare.io? Yes

**Describe the bug**  
As title says no loading straight to failed 

**Screenshots**  

**Logs**  
If applicable, post the part of the cvamp.log, that refers to the problem.

**Comment by BIGS772** [comment]
Never mind webshare have frozen my account for verification

**Comment by KevinBytesTheDust** [comment]
Please keep us updated if your verification succeeds.

**Comment by BIGS772** [comment]
Verification worked 💪
